version: '3'
services:
    nodejs:
        image: node_test
        build:
         context: ../apps/node_first_test
        container_name: node_test
        working_dir: /usr/src/app
        command: node app.js
        ports:
            - "80:80"
        environment:
            NODE_ENV: development
        volumes:
            - ../apps/node_first_test/app:/usr/src/app
        networks:
            app_net:
                ipv4_address: 172.16.250.10
networks:
    app_net:
        driver: bridge
        ipam:
            driver: default
            config:
                -   subnet: 172.16.250.0/24